filebeat.prospectors:
 - input_type: log
   paths:
    - /var/log/*.log
   input_type: log
   document_type: syslog
   registry: /var/lib/filebeat/registry
output.logstash:
  hosts: ["10.0.0.1:5044"]
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  rotateeverybytes: 10485760

