filebeat.prospectors:
 - input_type: log
   paths:
    - /etc/filebeat/testdata/*.log
output:
  logstash:
    hosts: ["logstash:5044"]
    index: filebeat

logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  rotateeverybytes: 10485760

